# Generated by Django 5.1.1 on 2024-09-18 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('departamento', models.CharField(max_length=150, verbose_name='Departamento')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('status', models.CharField(default='Pendente', max_length=150, verbose_name='Status')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/', verbose_name='Anexo')),
            ],
        ),
    ]
