# Generated by Django 5.1.1 on 2024-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='status',
            field=models.CharField(choices=[('M', 'Pendente'), ('P', 'Concluído')], max_length=1, verbose_name='Status'),
        ),
    ]
